USE [ProyectoIntegrado]
GO

/****** Object:  Table [dbo].[VISITA]    Script Date: 06/06/2024 13:37:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VISITA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_PACIENTE] [int] NOT NULL,
	[ID_MEDICO] [int] NOT NULL,
	[ID_ENFERMEDAD] [int] NOT NULL,
	[ID_MEDICAMENTO] [int] NOT NULL,
	[MOTIVO] [varchar](200) NULL,
	[FECHA_VISITA] [datetime2](7) NULL,
 CONSTRAINT [PK_VISITA_PACIENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VISITA]  WITH CHECK ADD  CONSTRAINT [FK_VISITA_ENFERMEDAD] FOREIGN KEY([ID_ENFERMEDAD])
REFERENCES [dbo].[ENFERMEDAD] ([ID])
GO

ALTER TABLE [dbo].[VISITA] CHECK CONSTRAINT [FK_VISITA_ENFERMEDAD]
GO

ALTER TABLE [dbo].[VISITA]  WITH CHECK ADD  CONSTRAINT [FK_VISITA_MEDICAMENTO] FOREIGN KEY([ID_MEDICAMENTO])
REFERENCES [dbo].[MEDICAMENTO] ([ID])
GO

ALTER TABLE [dbo].[VISITA] CHECK CONSTRAINT [FK_VISITA_MEDICAMENTO]
GO

ALTER TABLE [dbo].[VISITA]  WITH CHECK ADD  CONSTRAINT [FK_VISITA_MEDICO] FOREIGN KEY([ID_MEDICO])
REFERENCES [dbo].[MEDICO] ([ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[VISITA] CHECK CONSTRAINT [FK_VISITA_MEDICO]
GO

ALTER TABLE [dbo].[VISITA]  WITH CHECK ADD  CONSTRAINT [FK_VISITA_PACIENTE] FOREIGN KEY([ID_PACIENTE])
REFERENCES [dbo].[PACIENTE] ([ID])
GO

ALTER TABLE [dbo].[VISITA] CHECK CONSTRAINT [FK_VISITA_PACIENTE]
GO


