USE [ProyectoIntegrado]
GO

/****** Object:  Table [dbo].[VISITA_SINTOMA_ENFERMEDAD]    Script Date: 06/06/2024 13:37:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[VISITA_SINTOMA_ENFERMEDAD](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_VISITA] [int] NOT NULL,
	[ID_SINTOMA_ENFERMEDAD] [int] NOT NULL,
 CONSTRAINT [PK_VISITA_SINTOMA_ENFERMEDAD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[VISITA_SINTOMA_ENFERMEDAD]  WITH CHECK ADD  CONSTRAINT [FK_D4687DFF] FOREIGN KEY([ID_VISITA])
REFERENCES [dbo].[VISITA] ([ID])
GO

ALTER TABLE [dbo].[VISITA_SINTOMA_ENFERMEDAD] CHECK CONSTRAINT [FK_D4687DFF]
GO

ALTER TABLE [dbo].[VISITA_SINTOMA_ENFERMEDAD]  WITH CHECK ADD  CONSTRAINT [FK_VISITA_SINTOMA_ENFERMEDAD_SINTOMA_ENFERMEDAD] FOREIGN KEY([ID_SINTOMA_ENFERMEDAD])
REFERENCES [dbo].[SINTOMA_ENFERMEDAD] ([ID])
GO

ALTER TABLE [dbo].[VISITA_SINTOMA_ENFERMEDAD] CHECK CONSTRAINT [FK_VISITA_SINTOMA_ENFERMEDAD_SINTOMA_ENFERMEDAD]
GO

ALTER TABLE [dbo].[VISITA_SINTOMA_ENFERMEDAD]  WITH CHECK ADD  CONSTRAINT [FK_VISITA_SINTOMA_ENFERMEDAD_VISITA] FOREIGN KEY([ID_VISITA])
REFERENCES [dbo].[VISITA] ([ID])
GO

ALTER TABLE [dbo].[VISITA_SINTOMA_ENFERMEDAD] CHECK CONSTRAINT [FK_VISITA_SINTOMA_ENFERMEDAD_VISITA]
GO


